include ../Makefile

fork:	fork.go
vfork:	vfork.go
wait:	wait.go
fork2: 	fork2.go
tellwait1: tellwait1.go
echoall: echoall.go
exec: exec.go
bash: bash.go
test1: test1.go
pacct: pacct.go
nice: nice.go
